### ISSUE TITLE
redis 6.0.3无法使用cli，用其他工具是能正常连接的

### ISSUE THREAD

**Issue by fasnow** [yuyan-sec/RedisEXP#10]
![image](https://github.com/yuyan-sec/RedisEXP/assets/40886524/716da180-7e6f-4ca4-8ac7-0da08f67b419)
![image](https://github.com/yuyan-sec/RedisEXP/assets/40886524/d0c71680-e868-4149-bbd7-286c5b304435)

**Comment by yuyan-sec** [comment]
@fasnow 
redis 远程主机强行关闭了一个现有连接，有可能配置了最大连接数。
