### ISSUE TITLE
你好无法生成 ssrf gopher payload

### ISSUE THREAD

**Issue by 0x6C696A756E** [yuyan-sec/RedisEXP#11]
<img width="748" alt="搜狗截图20240115073444" src="https://github.com/yuyan-sec/RedisEXP/assets/139900234/7dda0096-8a49-4ab3-a19d-6582dc8ec413">

**Comment by yuyan-sec** [comment]
@0x6C696A756E 1.txt是你本地要读取的模板内容，你当前目录没 1.txt 这个文件

**Comment by 0x6C696A756E** [comment]
1.txt内容能否给个实例？大哥

**Comment by yuyan-sec** [comment]
@0x6C696A756E https://github.com/firebroo/sec_tools/tree/master/redis-over-gopher
