### ISSUE TITLE
go build error

### ISSUE THREAD

**Issue by M00nT0** [yuyan-sec/RedisEXP#2]
go build main.go

go: downloading github.com/go-redis/redis/v8 v8.11.5
go: downloading github.com/cespare/xxhash/v2 v2.1.2
go: downloading github.com/dgryski/go-rendezvous v0.0.0-20200823014737-9f7001d12a5f
# RedisExp/pkg
..\pkg\slave.go:37:17: undefined: io.ReadAll
..\pkg\upload.go:36:17: undefined: io.ReadAll
note: module requires Go 1.17

**Comment by yuyan-sec** [comment]
@Gofreedom0 我本地编译了没问题啊，你的go版本是什么？

**Comment by yad1d1** [comment]
使用 Go 1.17 编译没有问题，正常使用，这个报错可能是因为 go.mod文件里面配置的Go版本是1.17
