### ISSUE TITLE
对-ssh参数的一个建议

### ISSUE THREAD

**Issue by yad1d1** [yuyan-sec/RedisEXP#4]
-ssh 参数，默认进行 `config set dir /root/.ssh/`，能否支持自定义这个路径

**Comment by yuyan-sec** [comment]
@yad1d1 你输入 root 用户就是 /root/.ssh ，你输入其他用户，例如：kali 就是 /home/kali/.ssh

**Comment by yad1d1** [comment]
@yuyan-sec 确实发现可以基于用户名来做路径适配，但还是有些意外的情况，上周末复现时发现Kali里面的 openssh-server 的配置地址默认貌似是 /.ssh 而不是 /root/.ssh

**Comment by yuyan-sec** [comment]
@yad1d1 https://github.com/yuyan-sec/RedisEXP/blob/main/pkg/echo.go#L39 判断如果存在 / 就自定义了

**Comment by yad1d1** [comment]
@yuyan-sec 👍👍👍👍
