### ISSUE TITLE
go build 报错

### ISSUE THREAD

**Issue by t1gress** [yuyan-sec/RedisEXP#7]
师傅您好，我build报错如下信息，请问是必须要1.17的环境才能编译吗
RedisEXP\cmd>go build main.go
go: downloading github.com/axgle/mahonia v0.0.0-20180208002826-3358181d7394
go: downloading github.com/go-redis/redis/v8 v8.11.5
..\pkg\lua.go:6:2: github.com/axgle/mahonia@v0.0.0-20180208002826-3358181d7394: Get "https://proxy.golang.org/github.com/axgle/mahonia/@v/v0.0.0-20180208002826-3358181d7394.zip": dial tcp 172.217.160.113:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
..\pkg\Redis.go:9:2: github.com/go-redis/redis/v8@v8.11.5: Get "https://proxy.golang.org/github.com/go-redis/redis/v8/@v/v8.11.5.zip": dial tcp 172.217.160.113:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

>go version
go version go1.18.4 windows/amd64

**Comment by yuyan-sec** [comment]
@cheng1107 应该是下载包的问题，设置一下国内代理，打开你的终端并执行
```
go env -w GO111MODULE=on
go env -w GOPROXY=https://goproxy.cn,direct
```

**Comment by t1gress** [comment]
> 

好的，谢谢师傅~
