### ISSUE TITLE
提出一个bug，会导致爆破redis密码失败

### ISSUE THREAD

**Issue by 1ighttack** [yuyan-sec/RedisEXP#8]
出问题的位置为
https://github.com/yuyan-sec/RedisEXP/blob/15f98de8d91d716f4a39bb5c8835216c731f8b8a/pkg/Redis.go#L34

这里输入的值应该是PING，PONG会报错导致爆破redis密码失败

**Comment by 1ighttack** [comment]
![图片](https://user-images.githubusercontent.com/71672296/204747418-715f75fd-b7f3-4c20-adf7-7047c9444ca9.png)

**Comment by yuyan-sec** [comment]
@1ighttack PONG 是返回值，不是输入的值。Rdb.Ping(ctx).Result() 才是执行 ping，可能是爆破的并发没写好所以没爆破成功

**Comment by 1ighttack** [comment]
emm是我代码没看仔细，PONG确实是判断的返回值，但是改成PING爆破是成功 （雾

**Comment by yuyan-sec** [comment]
@1ighttack 你的字典是在linux创建的吗？我发现在Linux创建的字典爆破 不成功，在windows创建的字典可以爆破成功。我也一头雾水

**Comment by yuyan-sec** [comment]
@1ighttack https://github.com/yuyan-sec/RedisEXP/blob/5c0b3375781cee08806c209ec7840191e15216ae/pkg/tools.go#L30 更新一下代码试一试，应该是 windows 和 linux 读取文件  换行和回车 的问题。

**Comment by 1ighttack** [comment]
嗯嗯更新之后可以了，谢谢师傅
<img width="375" alt="图片" src="https://user-images.githubusercontent.com/71672296/205431616-01056015-166a-4be0-9820-06282e8204c5.png">
